### ISSUE TITLE
syslog-ng syslog function

### ISSUE THREAD

**Issue by d-malko** [Graylog2/graylog-guide-syslog-linux#6]
Thank you, for you advice! I am using syslog-ng.
`destination graylog2 {
        syslog(77.121.15.94 port(8514));
        };
 `
I've got syntax error. When using quotes same result "77.121.15.94". 
Can you advice something? Should I add syslog function to syslog-ng?

**Comment by joschi** [comment]
@d-malko What's the exact error message you get?

**Comment by joschi** [comment]
Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
